args:
  batch_size: 16
  data_path: /mnt/G-SSD/BRACIS/slovo_tensors_32
  dataset: slovo
  exp_name: slovo_pretrain_all_best_augs_seed_42
  finetune: null
  frames: 16
  freeze: false
  gpus: 3
  learning_rate: 0.0001
  max_epochs: 1000
  mixup: true
  mixup_alpha: 0.25
  n_samples_per_class: null
  no_pretrain: false
  optimizer: adamw
  pretrained_model: MCG-NJU/videomae-base-finetuned-kinetics
  random_sample: true
  scheduler: plateau
  seed: 42
  specific_classes: null
  transforms:
  - normalize
  - color_jitter
  - random_rotation
  - random_perspective
  transforms_parameters:
  - color_jitter_0.4_0.4_0.4_0.4
  - random_rotation_35
  - random_perspective_0.5
  workers: 4
cache_dir: /mnt/G-SSD/BRACIS/BRACIS-2024/cache
lr: 0.0001
model_name: MCG-NJU/videomae-base-finetuned-kinetics
num_classes: 1001
optimizer: adamw
scheduler: plateau
