args:
  batch_size: 16
  data_path: /mnt/G-SSD/BRACIS/WLASL_tensors_32_complete
  dataset: wlasl
  exp_name: WLASL_300_classes_all_best_augs_pretrain_seed_42
  finetune: null
  frames: 16
  freeze: false
  gpus: 5
  learning_rate: 0.0001
  max_epochs: 200
  mixup: true
  mixup_alpha: 10.0
  n_samples_per_class: null
  no_pretrain: false
  optimizer: adamw
  pretrained_model: MCG-NJU/videomae-base-finetuned-kinetics
  random_sample: true
  scheduler: plateau
  seed: 42
  specific_classes: null
  transforms:
  - normalize
  - color_jitter
  - random_perspective
  - random_rotation
  transforms_parameters:
  - random_perspective_0.5
  - random_rotation_40
  - color_jitter_0.5_0.5_0.5_0.5
  workers: 16
cache_dir: /mnt/G-SSD/BRACIS/BRACIS-2024/cache
lr: 0.0001
model_name: MCG-NJU/videomae-base-finetuned-kinetics
num_classes: 2000
optimizer: adamw
scheduler: plateau
