args:
  batch_size: 16
  data_path: ../MINDS_tensors_32
  dataset: minds
  exp_name: fine_tuning_test_freeze_small_augs
  finetune: /mnt/E-SSD/BRACIS-2024/lightning_logs/slovo_pretrain/version_0/checkpoints/best_model_backup.ckpt
  frames: 16
  freeze: true
  gpus: 1
  learning_rate: 0.0001
  max_epochs: 1000
  n_samples_per_class: null
  no_pretrain: false
  optimizer: adamw
  pretrained_model: MCG-NJU/videomae-base-finetuned-kinetics
  random_sample: true
  scheduler: plateau
  seed: 42
  specific_classes: null
  transforms:
  - color_jitter
  - random_perspective
  - random_horizontal_flip
  - gaussian_blur
  - normalize
  workers: 4
cache_dir: ./cache
lr: 0.0001
model_name: MCG-NJU/videomae-base-finetuned-kinetics
num_classes: 20
optimizer: adamw
scheduler: plateau
