args:
  batch_size: 16
  data_path: /mnt/G-SSD/BRACIS/slovo_tensors_32/slovo_tensors_32
  dataset: slovo
  exp_name: scheduler_ES50_MAXEPOCHS600_slovo_pretrain_seed_44
  finetune: null
  frames: 16
  freeze: false
  gpus: 1
  learning_rate: 0.001
  max_epochs: 600
  mixup: false
  mixup_alpha: 1.0
  n_samples_per_class: null
  no_pretrain: false
  optimizer: adamw
  pretrained_model: MCG-NJU/videomae-base-finetuned-kinetics
  random_sample: true
  scheduler: linearlr
  seed: 44
  specific_classes: null
  transforms:
  - normalize
  transforms_parameters: null
  workers: 4
cache_dir: ./cache
lr: 0.001
model_name: MCG-NJU/videomae-base-finetuned-kinetics
num_classes: 1001
optimizer: adamw
scheduler: linearlr
