args:
  batch_size: 8
  data_path: ../MINDS_tensors_32
  exp_name: timesformer_sample_from_32
  frames: 16
  gpus: 2
  learning_rate: 0.0001
  max_epochs: 1000
  optimizer: adamw
  pretrained_model: facebook/timesformer-base-finetuned-k400
  random_sample: true
  scheduler: plateau
  seed: 42
  specific_classes: null
  transforms:
  - color_jitter
  - random_perspective
  - random_horizontal_flip
  - gaussian_blur
  - normalize
  workers: 4
cache_dir: ./cache
lr: 0.0001
model_name: facebook/timesformer-base-finetuned-k400
num_classes: 20
optimizer: adamw
scheduler: plateau
