args:
  batch_size: 4
  data_path: ../MINDS_tensors_all_frames
  exp_name: vivit_sample_from_all
  frames: 32
  gpus: 2
  learning_rate: 0.0001
  max_epochs: 1000
  n_samples_per_class: null
  optimizer: adamw
  pretrained_model: google/vivit-b-16x2-kinetics400
  random_sample: true
  scheduler: plateau
  seed: 42
  specific_classes: null
  transforms:
  - color_jitter
  - random_perspective
  - random_horizontal_flip
  - gaussian_blur
  - normalize
  workers: 4
cache_dir: ./cache
lr: 0.0001
model_name: google/vivit-b-16x2-kinetics400
num_classes: 20
optimizer: adamw
scheduler: plateau
